#!/usr/bin/env zsh

file_path=$(readlink -f "${0}")
root_path=$(dirname $(dirname $file_path))
tool_dir=$(basename $(dirname $file_path))
name="google-cloud-sdk"

gcloud_sdk=$tool_dir/${name}

if [ -f "${gcloud_sdk}/path.zsh.inc" ]; then
  source "${gcloud_sdk}/path.zsh.inc";
fi

if [ -f "${gcloud_sdk}/completion.zsh.inc" ]; then
  source "${gcloud_sdk}/completion.zsh.inc";
fi
