#!/bin/sh
set -eu

file_path=$(readlink -f "${0}")
root_path=$(dirname $(dirname $file_path))
tool_dir=$(basename $(dirname $file_path))
name="google-cloud-sdk"
arch="linux-x86_64"

# https://cloud.google.com/sdk/docs/quickstart-linux
version="269.0.0"
checksum="f152815d05a2f9374c87be1325a7d3bdbf62720d8fad9acb42dc2312d2e33f4a"

package_base_url="https://dl.google.com/dl/cloudsdk/channels/rapid/downloads"
package_file="${name}-${version}-${arch}.tar.gz"

indent() {
  sed -u 's/^/       /'
}

echo "Platform: ${arch}"
echo "Version: ${version}"
echo ""

mkdir -p $root_path/$tool_dir
cd $root_path/$tool_dir

echo "-----> Fetching into: ${root_path}/${tool_dir}"
curl -sL $package_base_url/$package_file -o $package_file

# check sha256 checksum
echo "${checksum}" "" ./$package_file | sha256sum -c - | indent

echo "-----> Deleting old sdk (if exists)"
rm -fr "./${name}"

echo "-----> Extracting new sdk"
tar zxf $package_file | indent

# setup $tool_dir as a root for sdk
echo "-----> Running install.sh ..args > install.log"
CLOUDSDK_ROOT_DIR=. ./$name/install.sh \
  --command-completion=false \
  --usage-reporting=false \
  --path-update=false \
  --rc-path=/dev/null \
  --override-components beta cloud-build-local core \
  --quiet > $name/install.log

echo "-----> Done"
cd $root_path

# print instructions
source_cmd="source ${root_path}/${tool_dir}/load-gcloud"
init_cmd="gcloud init"
update_cmd="gcloud components update"

echo "Run \`${source_cmd}\`" | indent
echo "Then init by \`${init_cmd}\` and update with \`${update_cmd}\`" | indent

echo "-----> Bye"
